services:
  - type: web
    name: schedule
    env: php
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader && npm ci && npm run build
    startCommand: php artisan serve
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        fromDatabase:
          name: schedule
          property: app_key
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: schedule
          property: host
      - key: DB_PORT
        fromDatabase:
          name: schedule
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: schedule
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: schedule
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: schedule
          property: password
    healthCheckPath: /health